export const POSTURE_THRESHOLDS = {
  minimumLandmarkVisibility: 0.55,
  levelShoulderDegrees: 4,
  noticeableShoulderDegrees: 8,
  torsoLeanRatio: 0.16,
  shoulderCenterOffset: 0.18,
  tooCloseShoulderWidth: 0.62,
  tooFarShoulderWidth: 0.18,
  tooHighNoseY: 0.08,
  tooLowNoseY: 0.36,
  smoothingFactor: 0.28,
  postureGuidanceMs: 3_000,
  prolongedPostureEventMs: 8_000,
  framingGuidanceMs: 2_000,
  framingEventMs: 6_000,
  movementWindowMs: 10_000,
  excessiveTransitions: 6,
  poseIntervalMs: 360,
} as const;
