export const HAND_THRESHOLDS = {
  minimumDetectionConfidence: 0.55,
  faceMarginRatio: 0.15,
  partialFaceOverlap: 0.1,
  significantFaceOverlap: 0.3,
  cameraObstructionArea: 0.28,
  significantMovementDistance: 0.09,
  smoothingFactor: 0.3,
  handIntervalMs: 360,
  nearFaceGuidanceMs: 2_000,
  nearFaceEventMs: 5_000,
  faceObstructionGuidanceMs: 1_500,
  faceObstructionEventMs: 4_000,
  cameraObstructionGuidanceMs: 1_000,
  cameraObstructionEventMs: 3_000,
  excessiveMovementGuidanceMs: 5_000,
  excessiveMovementEventMs: 10_000,
  movementWindowMs: 10_000,
  excessiveDirectionChanges: 8,
} as const;
